SMALL_Y_DEFECT_ELECTRODE = {
    # (1) 검사불량데이터상 고빈도 불량코드
    # 데이터 소스 : 검사불량데이터 / MES
    "검사불량이력": [
        "y_MES_Electrode_Slitting_Anode_외관-변형-분화구-표면",  # '외관-변형-분화구-표면'
        "y_MES_Electrode_Slitting_Cathode_외관-변형-분화구-표면",  # '외관-변형-분화구-표면',
        "y_MES_Electrode_Slitting_Anode_외관-변형-크랙-표면",  # '외관-변형-크랙-표면',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-크랙-표면",  # '외관-변형-크랙-표면',
        "y_MES_Electrode_Slitting_Anode_무지부_주름",  # '무지부_주름',
        "y_MES_Electrode_Slitting_Cathode_무지부_주름",  # '무지부_주름',
        "y_MES_Electrode_Slitting_Anode_치수-위치도-규격이탈-Mismatch",  # '치수-위치도-규격이탈-Mismatch',
        "y_MES_Electrode_Slitting_Cathode_치수-위치도-규격이탈-Mismatch",  # '치수-위치도-규격이탈-Mismatch',
        "y_MES_Electrode_Slitting_Anode_외관-변형-Pin hole-표면",  # '외관-변형-Pin hole-표면',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-Pin hole-표면",  # '외관-변형-Pin hole-표면',
        "y_MES_Electrode_Slitting_Anode_미세라인",  # '미세라인',
        "y_MES_Electrode_Slitting_Cathode_미세라인",  # '미세라인',
        "y_MES_Electrode_Slitting_Anode_외관-손상-찍힘/눌림-찍힘",  # '외관-손상-찍힘/눌림-찍힘',
        "y_MES_Electrode_Slitting_Cathode_외관-손상-찍힘/눌림-찍힘",  # '외관-손상-찍힘/눌림-찍힘',
        "y_MES_Electrode_Slitting_Anode_무지부_아일랜드(절연액)",  # '무지부_아일랜드(절연액)',
        "y_MES_Electrode_Slitting_Cathode_무지부_아일랜드(절연액)",  # '무지부_아일랜드(절연액)',
        "y_MES_Electrode_Slitting_Anode_외관-손상-탈리-단선",  # '외관-손상-탈리-단선',
        "y_MES_Electrode_Slitting_Cathode_외관-손상-탈리-단선",  # '외관-손상-탈리-단선',
        "y_MES_Electrode_Slitting_Anode_치수-폭-규격이탈-무지부",  # '치수-폭-규격이탈-무지부',
        "y_MES_Electrode_Slitting_Cathode_치수-폭-규격이탈-무지부",  # '치수-폭-규격이탈-무지부',
        "y_MES_Electrode_Slitting_Anode_치수-폭-규격이탈-코팅부",  # '치수-폭-규격이탈-코팅부',
        "y_MES_Electrode_Slitting_Cathode_치수-폭-규격이탈-코팅부",  # '치수-폭-규격이탈-코팅부',
        "y_MES_Electrode_Slitting_Anode_두께",  # '두께',
        "y_MES_Electrode_Slitting_Cathode_두께",  # '두께',
        "y_MES_Electrode_Slitting_Anode_외관-변형-전극 라인-표면",  # '외관-변형-전극 라인-표면',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-전극 라인-표면",  # '외관-변형-전극 라인-표면',
        "y_MES_Electrode_Slitting_Anode_외관-변형-아일랜드-표면",  # '외관-변형-아일랜드-표면',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-아일랜드-표면",  # '외관-변형-아일랜드-표면',
        "y_MES_Electrode_Slitting_Anode_절연_GAP",  # '절연_GAP',
        "y_MES_Electrode_Slitting_Cathode_절연_GAP",  # '절연_GAP',
        "y_MES_Electrode_Slitting_Anode_유지부_스크래치",  # '유지부_스크래치',
        "y_MES_Electrode_Slitting_Cathode_유지부_스크래치",  # '유지부_스크래치',
        "y_MES_Electrode_Slitting_Anode_절연 폭",  # '절연 폭',
        "y_MES_Electrode_Slitting_Cathode_절연 폭",  # '절연 폭',
        "y_MES_Electrode_Slitting_Anode_코팅부_주름",  # '코팅부_주름',
        "y_MES_Electrode_Slitting_Cathode_코팅부_주름",  # '코팅부_주름',
        "y_MES_Electrode_Slitting_Anode_절연_아일랜드(활물질)",  # '절연_아일랜드(활물질)',
        "y_MES_Electrode_Slitting_Cathode_절연_아일랜드(활물질)",  # '절연_아일랜드(활물질)',
        "y_MES_Electrode_Slitting_Anode_외관-변형-Side Ring-표면",  # '외관-변형-Side Ring-표면',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-Side Ring-표면",  # '외관-변형-Side Ring-표면',
        "y_MES_Electrode_Slitting_Anode_유지부_돌출",  # '유지부_돌출',
        "y_MES_Electrode_Slitting_Cathode_유지부_돌출",  # '유지부_돌출',
        "y_MES_Electrode_Slitting_Anode_외관-변형-접힘-접힘",  # '외관-변형-접힘-접힘',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-접힘-접힘",  # '외관-변형-접힘-접힘',
        "y_MES_Electrode_Slitting_Anode_유지부_SLT면_탈리",  # '유지부_SLT면_탈리',
        "y_MES_Electrode_Slitting_Cathode_유지부_SLT면_탈리",  # '유지부_SLT면_탈리',
        "y_MES_Electrode_Slitting_Anode_외관-변형-미압연-표면",  # '외관-변형-미압연-표면',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-미압연-표면",  # '외관-변형-미압연-표면',
        "y_MES_Electrode_Slitting_Anode_절연_LINE",  # '절연_LINE',
        "y_MES_Electrode_Slitting_Cathode_절연_LINE",  # '절연_LINE',
        "y_MES_Electrode_Slitting_Anode_외관-변형-열주름-표면",  # '외관-변형-열주름-표면',
        "y_MES_Electrode_Slitting_Cathode_외관-변형-열주름-표면",  # '외관-변형-열주름-표면',
        "y_MES_Electrode_Coating_Anode_외관_표면 (Top)",  # '외관_표면 (Top)',
        "y_MES_Electrode_Coating_Cathode_외관_표면 (Top)",  # '외관_표면 (Top)',
        "y_MES_Electrode_Coating_Anode_외관_표면 (Back)",  # '외관_표면 (Back)',
        "y_MES_Electrode_Coating_Cathode_외관_표면 (Back)",  # '외관_표면 (Back)',
        "y_MES_Electrode_Coating_Anode_치수_Mismatch (Back)",  # '치수_Mismatch (Back)',
        "y_MES_Electrode_Coating_Cathode_치수_Mismatch (Back)", # '치수_Mismatch (Back)',
        "y_MES_Electrode_Coating_Anode_절연 (Top)",  # '절연 (Top)',
        "y_MES_Electrode_Coating_Cathode_절연 (Top)",  # '절연 (Top)',
        "y_MES_Electrode_Coating_Anode_치수_Loading (Back)",  # '치수_Loading (Back)',
        "y_MES_Electrode_Coating_Cathode_치수_Loading (Back)",  # '치수_Loading (Back)',
        "y_MES_Electrode_Coating_Anode_절연 (Back)",  # '절연 (Back)',
        "y_MES_Electrode_Coating_Cathode_절연 (Back)",  # '절연 (Back)',
        "y_MES_Electrode_Coating_Anode_치수_Loading (Top)",  # '치수_Loading (Top)',
        "y_MES_Electrode_Coating_Cathode_치수_Loading (Top)",  # '치수_Loading (Top)',
        "y_MES_Electrode_Coating_Anode_외관_접힘 (Back)",  # '외관_접힘 (Back)',
        "y_MES_Electrode_Coating_Cathode_외관_접힘 (Back)",  # '외관_접힘 (Back)',
        "y_MES_Electrode_Slitting_Anode_연결-반제품",  # '연결-반제품',
        "y_MES_Electrode_Slitting_Cathode_연결-반제품",  # '연결-반제품',
        "y_MES_Electrode_Coating_Anode_외관_단선 (Top)", #"외관_단선 (Top)"
        "y_MES_Electrode_Coating_Cathode_외관_단선 (Top)", #"외관_단선 (Top)"
        "y_MES_Electrode_Coating_Anode_외관_단선 (Back)", #"외관_단선 (Back)"
        "y_MES_Electrode_Coating_Cathode_외관_단선 (Back)", #"외관_단선 (Back)"
        "y_MES_Electrode_Roll Pressing_Anode_치수_두께",  # '치수_두께',
        "y_MES_Electrode_Roll Pressing_Cathode_치수_두께",  # '치수_두께',
        "y_MES_Electrode_Roll Pressing_Anode_외관_찍힘",  # '외관_찍힘',
        "y_MES_Electrode_Roll Pressing_Cathode_외관_찍힘",  # '외관_찍힘',
        "y_MES_Electrode_Coating_Anode_외관_접힘 (Top)", #"외관_접힘 (Top)"
        "y_MES_Electrode_Coating_Cathode_외관_접힘 (Top)", #"외관_접힘 (Top)"
        "y_MES_Electrode_Roll Pressing_Anode_외관_접힘", #"외관_접힘"
        "y_MES_Electrode_Roll Pressing_Cathode_외관_접힘", #"외관_접힘" 
        "y_MES_Electrode_Roll Pressing_Anode_연결-반제품(Unwinder)", # '연결-반제품(Unwinder)'
        "y_MES_Electrode_Roll Pressing_Cathode_연결-반제품(Unwinder)", # '연결-반제품(Unwinder)'
        "y_MES_Electrode_Roll Pressing_Anode_표면_라인", #"표면_라인"
        "y_MES_Electrode_Roll Pressing_Cathode_표면_라인", #"표면_라인"
        "y_MES_Electrode_Roll Pressing_Anode_표면_라인", #"표면_라인"

    ],
    # (3) 주요 불량 유형에서 오는 불량 코드
    # 데이터 소스 : 생산이력데이터 / MES
    "생산이력데이터": [
        "y_MES_Electrode_Coating_Anode_치수_Loading (Back)",
        "y_MES_Electrode_Coating_Cathode_치수_Loading (Top)",
        "y_MES_Electrode_Coating_Anode_외관_표면 (Top)",
        "y_MES_Electrode_Coating_Cathode_외관_표면 (Top)",
        'y_MES_Electrode_Coating_Anode_외관_표면 (Back)',
        'y_MES_Electrode_Coating_Cathode_외관_표면 (Back)',
        'y_MES_Electrode_Coating_Anode_외관_단선 (Back)',
        'y_MES_Electrode_Coating_Cathode_외관_단선 (Back)',
        'y_MES_Electrode_Coating_Anode_외관_단선 (Back)',
        'y_MES_Electrode_Coating_Cathode_외관_단선 (Back)',
        "y_MES_Electrode_Roll Pressing_Anode_치수_두께",
        "y_MES_Electrode_Roll Pressing_Cathode_치수_두께",
        
        "y_MES_Electrode_Coating_Anode_치수-폭-규격이탈-무지부",
        "y_MES_Electrode_Coating_Cathode_치수-폭-규격이탈-무지부",
        "y_MES_Electrode_Coating_Anode_절연_폭",
        "y_MES_Electrode_Coating_Cathode_절연_폭",
        "y_MES_Electrode_Coating_Anode_치수-폭-규격이탈-코팅부",
        "y_MES_Electrode_Coating_Cathode_치수-폭-규격이탈-코팅부",

        'y_MES_Electrode_Coating_Anode_치수_폭(Back)',
        'y_MES_Electrode_Coating_Cathode_치수_폭(Back)',
        'y_MES_Electrode_Coating_Anode_치수_폭(Top)',
        'y_MES_Electrode_Coating_Cathode_치수_폭(Top)',

        "y_MES_Electrode_Coating_Cathode_불량 등록_외관-변형-크랙-표면",
        "y_MES_Electrode_Coating_Anode_불량 등록_외관-변형-크랙-표면",
    ],
    # 데이터 소스 : LQC
    "LQC": [
        'y_LQC_Electrode_Slitting_Anode_Camber',
        'y_LQC_Electrode_Slitting_Cathode_Camber',
        "y_LQC_Electrode_Slitting_Anode_Camber_1_측정값",  # 'Slitting_Camber_1_측정값'
        "y_LQC_Electrode_Slitting_Cathode_Camber_1_측정값",  # 'Slitting_Camber_1_측정값'
    ],
    # 데이터 소스 : 공정자주검사데이터
    # 데이터 소스 : 전수검사데이터(전극/조립/활성화, SPC+)
    "SPC": [

        'y_SPCP_Electrode_Appearance_Slitting_Anode_열주름_외관판정_NG_Count',
        'y_SPCP_Electrode_Appearance_Slitting_Cathode_열주름_외관판정_NG_Count',

        'y_SPCP_Electrode_Appearance_Slitting_Anode_코팅부_주름', #"코팅부 주름",
        'y_SPCP_Electrode_Appearance_Slitting_Cathode_코팅부_주름',
        "y_SPCP_Electrode_Appearance_Slitting_Anode_열주름", 
        "y_SPCP_Electrode_Appearance_Slitting_Cathode_열주름", 
        "y_SPCP_Electrode_Appearance_Slitting_Anode_미코팅부 주름",
        "y_SPCP_Electrode_Appearance_Slitting_Cathode_미코팅부 주름"
        ],
}

SMALL_Y_CTQ_ELECTRODE = {
    # 데이터 소스 : 공정자주 샘플링검사 데이터
    "공정자주샘플링검사": [
        # "Loading-TWS-Top/Back-Dry",
        # "Loading-TWS-Top/Back-Dry",
    ],
    # 데이터 소스 : LQC
    "LQC": [
        # 'Sliding(-)_Tab Top/Back',
        'y_LQC_Electrode_Coating_Anode_Sliding (-)_Tab Back',
        'y_LQC_Electrode_Coating_Cathode_Sliding (-)_Tab Back',
        'y_LQC_Electrode_Coating_Anode_Sliding(+)_Tab Back',
        'y_LQC_Electrode_Coating_Cathode_Sliding(+)_Tab Back',
        'y_LQC_Electrode_Coating_Anode_Sliding (-)_Tab Top',
        'y_LQC_Electrode_Coating_Cathode_Sliding (-)_Tab Top',
        'y_LQC_Electrode_Coating_Anode_Sliding(+)_Tab Top',
        'y_LQC_Electrode_Coating_Cathode_Sliding(+)_Tab Top',

        "y_LQC_Electrode_Coating_Anode_Sliding(+)_Tab Back_5_측정값",
        "y_LQC_Electrode_Coating_Cathode_Sliding(+)_Tab Back_5_측정값",

        "y_LQC_Electrode_Coating_Anode_Sliding(+)_Tab Top_1_측정값",
        "y_LQC_Electrode_Coating_Anode_Sliding(+)_Tab Top_2_측정값",
        "y_LQC_Electrode_Coating_Anode_Sliding(+)_Tab Top_3_측정값",
        "y_LQC_Electrode_Coating_Anode_Sliding(+)_Tab Top_4_측정값",
        "y_LQC_Electrode_Coating_Cathode_Sliding(+)_Tab Top_1_측정값",
        "y_LQC_Electrode_Coating_Cathode_Sliding(+)_Tab Top_2_측정값",
        "y_LQC_Electrode_Coating_Cathode_Sliding(+)_Tab Top_3_측정값",
        "y_LQC_Electrode_Coating_Cathode_Sliding(+)_Tab Top_4_측정값",

        # 'Fat_edge_Fat_edge Tab Top/Back',
        'y_LQC_Electrode_Coating_Anode_Fat_edge_Tab Top',
        'y_LQC_Electrode_Coating_Cathode_Fat_edge_Tab Top',
        'y_LQC_Electrode_Coating_Anode_Fat_edge_Tab Back',
        'y_LQC_Electrode_Coating_Cathode_Fat_edge_Tab Back',

        "y_LQC_Electrode_Coating_Anode_Fat_edge_Tab Back_1_측정값",
        "y_LQC_Electrode_Coating_Anode_Fat_edge_Tab Back_4_측정값",
        "y_LQC_Electrode_Coating_Anode_Fat_edge_Tab Top_6_측정값",
        "y_LQC_Electrode_Coating_Cathode_Fat_edge_Tab Back_1_측정값",
        "y_LQC_Electrode_Coating_Cathode_Fat_edge_Tab Back_4_측정값",
        "y_LQC_Electrode_Coating_Cathode_Fat_edge_Tab Top_6_측정값",

        'y_LQC_Electrode_Roll Pressing_Anode_로딩',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량2',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량2',

        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_10_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_11_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_12_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_13_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_14_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_15_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_16_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_17_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_18_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_1_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_2_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_3_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_4_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_5_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_6_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_7_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_8_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_로딩_총 로딩량1_9_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_10_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_11_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_12_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_13_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_14_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_15_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_16_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_17_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_18_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_1_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_2_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_3_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_4_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_5_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_6_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_7_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_8_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_로딩_총 로딩량1_9_측정값',#"로딩_총 로딩량1",

        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Back',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Back',
        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Top',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Top',  

        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Back_1_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Back_2_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Back_3_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Back_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Top_1_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Top_2_측정값',
        'y_LQC_Electrode_Roll Pressing_Anode_접착력_Top_3_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Back_1_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Back_2_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Back_3_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Back_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Top_1_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Top_2_측정값',
        'y_LQC_Electrode_Roll Pressing_Cathode_접착력_Top_3_측정값',#"접착력_Top/Back",

        'y_LQC_Electrode_Slitting_Anode_수분_R2R Dry 후',
        'y_LQC_Electrode_Slitting_Cathode_수분_R2R Dry 후',

        "y_LQC_Electrode_Slitting_Anode_수분_R2R Dry 후_1_측정값",  # '수분_R2R Dry 후',
        "y_LQC_Electrode_Slitting_Anode_수분_R2R Dry 후_2_측정값",  # '수분_R2R Dry 후',
        "y_LQC_Electrode_Slitting_Cathode_수분_R2R Dry 후_1_측정값",  # '수분_R2R Dry 후',
        "y_LQC_Electrode_Slitting_Cathode_수분_R2R Dry 후_2_측정값",  # '수분_R2R Dry 후',
        'y_LQC_Electrode_Slitting_Anode_Camber',
        'y_LQC_Electrode_Slitting_Cathode_Camber',
        'y_LQC_Electrode_Slitting_Anode_Slitting Burr',
        'y_LQC_Electrode_Slitting_Cathode_Slitting Burr',
    ],
    # 데이터 소스 : 설비 파라미터(PV) 데이터
    "PV": [
        # 'PRESS THICKNESS AVERAGE (PV)'
        # 'PRESS THICKNESS AVERAGE (PV)'
        "X_PV_Electrode_Roll Pressing_Anode_W00715F_N_*",
        "X_PV_Electrode_Roll Pressing_Cathode_W00715F_N_*",
    ],
}


SMALL_Y_DEFECT_WINDING = {
    # (1) 검사불량데이터상 고빈도 불량코드
    # 데이터 소스 : 전수검사데이터(전극/조립/활성화, SPC+)
    "검사불량이력": [
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPWTH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TNBMSM",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPLNE",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPPHL",  # 'CTPPHL',
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPPTC",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPCRT",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPCRK"  # 'CTPCRK',
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPSCR",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPPRT",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPDEN",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_LSRSCP",  # 'LSRSCP',
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BSNWTH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABPCH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABHGT",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABSHP",  # 'TABSHP',
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_EDGBRR",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_ICPWTH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPWTH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TNBMSM",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPLNE",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPPHL",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPPTC",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPCRT",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPCRK",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPSCR",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPPRT",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTPDEN",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_LSRSCP",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BSNWTH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABPCH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABHGT",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABSHP",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_EDGBRR",  # 'EDGBRR',
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SEPWTH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SEPPTC",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SEPPHL",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SEPPOF",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_ATBRFD",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTBRFD",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BULGAP_O1",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BLCGAP_O1",
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_BUAGAP_M1',
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_BCAGAP_O1',
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_BCAGAP_M2',
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BCARVR",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BASGAP_M1",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BCSGAP_O1",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BASRVR",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_BCSRVR",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_JLROTD_A1",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SEPWTH",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SLTPOS_C1",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SLTPOS",
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABANG_A1',
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABANG_A3',
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABANG_C1',
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_TABANG_C3'
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SLTWRK",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_JLRCTM",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_JLRDEN",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_JLRSCR",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_SLDHGT",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTBFLD",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_FTFC",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTBFLD",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_FTFM",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTBFLD",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_FTFO",
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_CTBRFM",  # 'CTBRFM', #(양극)
        "y_SPCP_Assemble_Dimension_Winding_DIMENSION_ATBRFM",  # 'ATBRFM', #(음극)
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_CORRFM_C1',
        'y_SPCP_Assemble_Dimension_Winding_DIMENSION_CORRFM_A1',

        # (3) 주요 불량 유형에서 오는 불량 코드
        # 데이터 소스 : 검사불량이력데이터 / MES
        "Short",

        # 'X_SV_Assemble_Winding_Parameter Value_Hi-pot TEST Input',
        # 'X_SV_Assemble_Winding_Parameter Value_Hi-pot CHG Input',
        # 'X_SV_Assemble_Winding_Parameter Value_Hi-pot Test V Input',
        # 'X_SV_Assemble_Winding_Parameter Value_Hi-pot UPPER Input',
        # 'X_SV_Assemble_Winding_Parameter Value_Hi-pot DWELL Input',
        # 'X_SV_Assemble_Winding_Parameter Value_Hi-pot Range Input',
        # 'X_SV_Assemble_Winding_Parameter Value_Hi-pot CC Input',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_Hi-pot TEST Input',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_Hi-pot CHG Input',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_Hi-pot Test V Input',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_Hi-pot UPPER Input',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_Hi-pot DWELL Input',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_Hi-pot Range Input',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_Hi-pot CC Input',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_Hi-pot TEST Input',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_Hi-pot CHG Input',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_Hi-pot Test V Input',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_Hi-pot UPPER Input',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_Hi-pot DWELL Input',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_Hi-pot Range Input',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_Hi-pot CC Input',
        # 'X_SV_Assemble_Winding_Paramter Target Value_Hi-pot TEST Input',
        # 'X_SV_Assemble_Winding_Paramter Target Value_Hi-pot CHG Input',
        # 'X_SV_Assemble_Winding_Paramter Target Value_Hi-pot Test V Input',
        # 'X_SV_Assemble_Winding_Paramter Target Value_Hi-pot UPPER Input',
        # 'X_SV_Assemble_Winding_Paramter Target Value_Hi-pot DWELL Input',
        # 'X_SV_Assemble_Winding_Paramter Target Value_Hi-pot Range Input',
        # 'X_SV_Assemble_Winding_Paramter Target Value_Hi-pot CC Input'

        # "y_Winding_Hi-pot-Arc-Jelly Roll_Defect Qty",  # 'Hi-pot - Arc',
        # # 'Hi-pot - Open(접촉)',
        # "y_Winding_Hi-pot-Open(접촉)-Jelly Roll_Defect Qty",
        # "Short - Open(접촉)",
        # "y_Winding_Hi-pot-Hi-Pot 장비 불량-Jelly Roll_Defect Qty",  # 'Hi-pot - Hi-Pot 장비 불량',
        # # 'Hi-pot - Hi-Pot 통신/제어 불량',
        # "y_Winding_Hi-pot-Hi-Pot 통신/제어 불량-Jelly Roll_Defect Qty",
        # "y_Winding_Hi-pot-Hi-Pot 내전압-Jelly Roll_Defect Qty",  # 'Hi-pot - Hi-Pot 내전압',
        # # 'Hi-pot - Hi-Pot Charge Fail',
        # "y_Winding_Hi-pot-Hi-Pot Charge Fail-Jelly Roll_Defect Qty",
        # "y_Winding_Hi-pot-PD-Jelly Roll_Defect Qty",  # 'Hi-pot - PD',
        # # 'Hi-pot - Hii-Pot Low Fail',
        # "y_Winding_Hi-pot-Hii-Pot Low Fail-Jelly Roll_Defect Qty",

        "총고",
        # "y_Winding_기타-외관 J/R총고-Jelly Roll_Defect Qty",  # '기타 - 외관 J/R총고',
        # "y_Winding_Vision-외관(-) Reform-Jelly Roll_Defect Qty",  # 'Reform',
        # "y_Winding_Reform-1차-Jelly Roll_Defect Qty",  # 'Reform - 1차',
        # "y_Winding_Reform-2차-Jelly Roll_Defect Qty",  # 'Reform - 2차',

        # 'Vision - 외관(+) Reform',
        # 'X_SV_Assemble_Winding_Parameter Value_사행 Vision',
        # 'X_SV_Assemble_Winding_Parameter Spec LSL_사행 Vision',
        # 'X_SV_Assemble_Winding_Parameter Spec USL_사행 Vision',
        # 'X_SV_Assemble_Winding_Paramter Target Value_사행 Vision',
        # #         "y_Winding_Vision-외관(+) Reform-Jelly Roll_Defect Qty",
        # "Vision - 외관(-) Reform",
        # "기타",
        # "y_Winding_투입감기-(-)-Pancake_Defect Qty",  # '투입감기 - (-)',
        # "투입감기 - (+)",
        # "P3 - 배출불량",
        # "전극 - 찢어짐(-)",
        # "전극 - 찢어짐(+)",

        # # '위치정렬 Vision - Sepa 잔량 S7',
        # "Y_SV_Winding_위치정렬 Vision-Sepa 잔량 S7-Jelly Roll_Defect Qty",
        # "y_Winding_위치정렬 Vision-Sepa 잔량 S7-Jelly Roll_Defect Qty",
        # "y_Winding_위치정렬 Vision-J/R 없음-Jelly Roll_Defect Qty",  # '위치정렬 Vision - J/R 없음',
        # "y_Winding_기타-J/R ID 없음-Jelly Roll_Defect Qty",  # '기타 - J/R ID 없음',
        # "y_Winding_Vision-Burr (-)-Pancake_Defect Qty",  # 'Vision - Burr (-)',
        # "y_Winding_Vision-burr (+)-Pancake_Defect Qty",  # 'Vision - burr (+)',

        # # '위치 - Cut 음극(-)',
        # "Y_SV_Winding_위치-Cut 음극(-)-Pancake_Defect Qty",
        # "y_Winding_위치-Cut 음극(-)-Pancake_Defect Qty",
        # "Y_SV_Winding_위치-Cut 음극(-)-Jelly Roll_Defect Qty",
        # "y_Winding_위치-Cut 음극(-)-Jelly Roll_Defect Qty",
        # # '위치 - Cut 양극(+)',
        # "Y_SV_Winding_위치-Cut 양극(+)-Jelly Roll_Defect Qty",
        # "y_Winding_위치-Cut 양극(+)-Jelly Roll_Defect Qty",
        # "Y_SV_Winding_위치-Cut 양극(+)-Pancake_Defect Qty",
        # "y_Winding_위치-Cut 양극(+)-Pancake_Defect Qty",

        "y_Winding_삽입-(-)-Pancake_Defect Qty",  # '삽입 - (-)',
        "y_Winding_삽입-(-)-Jelly Roll_Defect Qty",  # '삽입 - (-)',
        "y_Winding_삽입-(+)-Pancake_Defect Qty",  # '삽입 - (+)',
        "y_Winding_삽입-(+)-Jelly Roll_Defect Qty",  # '삽입 - (+)',
        "삽입 - 분리막",
        "y_Winding_Pattern 길이-양극 길이불량-Jelly Roll_Defect Qty",  # 'Pattern 길이 - 양극 길이불량',
        "y_Winding_Pattern 길이-양극 길이불량-Pancake_Defect Qty",  # 'Pattern 길이 - 양극 길이불량',
        # 'Pattern 길이 - 음극 길이불량',
        "Y_SV_Winding_Pattern 길이-음극 길이불량-Jelly Roll_Defect Qty",
        "Y_SV_Winding_Pattern 길이-음극 길이불량-Pancake_Defect Qty",
        "y_Winding_Pattern 길이-음극 길이불량-Pancake_Defect Qty",
        "y_Winding_Pattern 길이-음극 길이불량-Jelly Roll_Defect Qty",
        "y_Winding_부착-Seal-TAPE_Defect Qty",  # '부착 - Seal',
        # 'Vision - 외관 J/R표면',
        "Y_SV_Winding_Vision-외관 J/R표면-Jelly Roll_Defect Qty",
        "y_Winding_Vision-외관 J/R표면-Jelly Roll_Defect Qty",
        "y_Winding_Vision-외관 Seal Tape-Jelly Roll_Defect Qty",  # 'Vision - 외관 Seal Tape',
        "y_Winding_표면-(+)-Pancake_Defect Qty",  # '표면 - (-)',
        "y_Winding_표면-(-)-Pancake_Defect Qty",  # '표면 - (+)',
        "y_Winding_Vision-표면(-)-Pancake_Defect Qty",  # 'Vision - 표면(-)',
        "y_Winding_Vision-표면(+)-Pancake_Defect Qty",  # 'Vision - 표면(+)',
        "y_Winding_사행-(-)-Pancake_Defect Qty",  # '사행 - (-)',
        "y_Winding_사행-(+)-Pancake_Defect Qty",  # '사행 - (+)',
        "y_Winding_사행-분리막 1-분리막_Defect Qty",  # '사행 - 분리막 1',
        "y_Winding_사행-분리막 2-분리막_Defect Qty",  # '사행 - 분리막 2',
        "y_Winding_Vision-사행 분리막간 Gap-Separator_Defect Qty",  # 'Vision - 사행 분리막간 Gap',
        "y_Winding_Vision-사행 양극-분리막-Pancake_Defect Qty",  # 'Vision - 사행 양극-분리막',
        "Y_SV_Winding_Vision-사행 F1-Pancake_Defect Qty",  # 'Vision - 사행 F1',
        "y_Winding_Vision-사행 F2-Pancake_Defect Qty",  # 'Vision - 사행 F2',
        "y_Winding_Vision-사행 음극-분리막-Pancake_Defect Qty",  # 'Vision - 사행 음극-분리막',
        "Vision - 사행(-) AW1",
        "Vision - 사행(+) CW1",
        # 'Vision - 사행 음극-분리막(E1)',
        "y_Winding_Vision-사행 음극-분리막(E1)-Pancake_Defect Qty",
        # 'Vision - 사행 음극노칭골-분리막(AW1)',
        "Y_SV_Winding_Vision-사행 음극노칭골-분리막(AW1)-Pancake_Defect Qty",
        "y_Winding_Vision-사행 음극노칭골-분리막(AW1)-Pancake_Defect Qty",
        # 'Vision - 사행 양극노칭골-분리막(CW1)',
        "Y_SV_Winding_Vision-사행 양극노칭골-분리막(CW1)-Pancake_Defect Qty",
        "y_Winding_Vision-사행 양극노칭골-분리막(CW1)-Pancake_Defect Qty",
        # '위치정렬 Vision - 음극-분리막 E2',
        "Y_SV_Winding_위치정렬 Vision-음극-분리막 E2-Jelly Roll_Defect Qty",
        "y_Winding_위치정렬 Vision-음극-분리막 E2-Jelly Roll_Defect Qty",
        # 'Vision - Tab(+) Scrap',
        "Y_SV_Winding_Vision-Tab(+) Scrap-TAB_Defect Qty",
        "y_Winding_Vision-Tab(+) Scrap-TAB_Defect Qty",
        # 'Vision - Tab(+) 형상',
        "Y_SV_Winding_Vision-Tab(+) 형상-TAB_Defect Qty",
        "y_Winding_Vision-Tab(+) 형상-TAB_Defect Qty",
        # 'Vision - Tab(+) 노칭치수',
        "y_Winding_Vision-Tab(+) Notching Dimension-TAB_Defect Qty",
        # 'Vision - Tab(-) Scrap',
        "Y_SV_Winding_Vision-Tab(-) Scrap-TAB_Defect Qty",
        "y_Winding_Vision-Tab(-) Scrap-TAB_Defect Qty",
        # 'Vision - Tab(-) 노칭치수',
        "y_Winding_Vision-Tab(-) 노칭치수-TAB_Defect Qty",
        # 'Vision - Tab(-) 형상',
        "Y_SV_Winding_Vision-Tab(-) 형상-TAB_Defect Qty"
        "y_Winding_Vision-Tab(-) 형상-TAB_Defect Qty",
        "Vision - Tab(+) Px",
        "Vision - Tab(-) Px",
        # 'Vision - Tab(+) Height(AX)',
        "y_Winding_Vision-Tab(+) Height(AX)-TAB_Defect Qty",
        # 'Vision - Tab(+) Pitch(PX)',
        "y_Winding_Vision-Tab(+) Pitch(PX)-TAB_Defect Qty",
        # 'Vision - Tab(-) Height(AX)',
        "y_Winding_Vision-Tab(-) Height(AX)-TAB_Defect Qty",
        # 'Vision - Tab(-) Pitch(PX)',
        "Y_SV_Winding_Vision-Tab(-) Pitch(PX)-TAB_Defect Qty",
        "y_Winding_Vision-Tab(-) Pitch(PX)-TAB_Defect Qty",
        "Laser - Laser(-) 재시작",
        "Laser - Laser(+) 재시작",
        "y_Winding_Vision-외관 J/R분리막폭-Jelly Roll_Defect Qty",  # 'Vision - 외관 J/R분리막폭',
        "y_Winding_Vision-표면 분리막1 폭치수-Jelly Roll_Defect Qty",  # 'Vision - 표면 분리막1 폭치수',
        "y_Winding_Vision-표면 분리막2 폭치수-Jelly Roll_Defect Qty",  # 'Vision - 표면 분리막2 폭치수',
        # 'Vision - 사행(-) 투입량',
        "y_Winding_Vision-사행(-) 투입량-Jelly Roll_Defect Qty",
        "y_Winding_기타-코어투입량-Jelly Roll_Defect Qty",  # '기타 - 코어투입량',
        "y_Winding_투입량시스템-코어 투입량-분리막_Defect Qty",  # '투입량시스템 - 코어투입량',
        "y_Winding_투입량시스템-투입량 이상-Pancake_Defect Qty",  # '투입량시스템 - 투입량이상',
        # 'Vision - 사행(+) Tab접힘',
        "y_Winding_Vision-사행(+) Tab접힘-Jelly Roll_Defect Qty",
        # 'Vision - 사행(-) Tab접힘',
        "y_Winding_Vision-사행(-) Tab접힘-Jelly Roll_Defect Qty",
        # 'Vision - 표면-분리막1',
        "Y_SV_Winding_Vision-표면-분리막1-Separator_Defect Qty",
        "y_Winding_Vision-표면-분리막1-Separator_Defect Qty",
        "y_Winding_Vision-표면-분리막2-Separator_Defect Qty",  # 'Vision - 표면-분리막2',
        "y_Winding_Vision-외관 J/R외경-Jelly Roll_Defect Qty",  # 'Vision - 외관 J/R외경',
        # 'Vision - 주행 포밍(+) 치수',
        "y_Winding_Vision-주행 포밍(+) 치수-Pancake_Defect Qty",
        # 'Vision - 주행 포밍(-) 치수',
        "y_Winding_Vision-주행 포밍(-) 치수-Pancake_Defect Qty",
        # 'Vision - 외관 포밍각도(-)',
        "y_Winding_Vision-외관 포밍각도(-)-Jelly Roll_Defect Qty",
        # 'Vision - 외관 포밍각도(+)',
        "y_Winding_Vision-외관 포밍각도(+)-Jelly Roll_Defect Qty",
        # 'Vision - 주행 Forming Vision 검사기 리셋',
        "y_Winding_Vision-주행 Forming Vision 검사기 리셋-TAB_Defect Qty",
        "y_Winding_Vision-표면-분리막1 검사기 리셋-Jelly Roll_Defect Qty",  # 'Vision - 표면-분리막1 검사기 리셋',
        "y_Winding_Vision-표면-분리막1 검사기 리셋-Separator_Defect Qty",  # 'Vision - 표면-분리막1 검사기 리셋',
        "y_Winding_Vision-표면-분리막2 검사기 리셋-Jelly Roll_Defect Qty",  # 'Vision - 표면-분리막2 검사기 리셋',
        "y_Winding_Vision-표면-분리막2 검사기 리셋-Separator_Defect Qty",  # 'Vision - 표면-분리막2 검사기 리셋',
        "y_Winding_Vision-사행 피드백 없음-Pancake_Defect Qty",  # 'Vision - 사행 피드백 없음',
        # 'Vision - 외관 Vision J/R 없음',
        "y_Winding_Vision-외관 Vision J/R 없음-Jelly Roll_Defect Qty",
        # 'Vision - 외관 Vision 피드백 없음',
        "y_Winding_Vision-외관 Vision 피드백 없음-Jelly Roll_Defect Qty",
        # 'Vision - 외관 포밍 비전 J/R 없음',
        "y_Winding_Vision-외관 포밍 비전 J/R 없음-Jelly Roll_Defect Qty",
        # 'Vision - 외관 포밍 비전 피드백 없음',
        "y_Winding_Vision-외관 포밍 비전 피드백 없음-Jelly Roll_Defect Qty",
        # 'Vision - Tab(+) 검사기 리셋',
        "y_Winding_Vision-Tab(+) 검사기 리셋-TAB_Defect Qty",
        # 'Vision - Tab(-) 검사기 리셋',
        "y_Winding_Vision-Tab(-) 검사기 리셋-TAB_Defect Qty",
        # 'Vision - 표면(+) 검사기 리셋',
        "y_Winding_Vision-표면(+) 검사기 리셋-Pancake_Defect Qty",
        # 'Vision - 표면(-) 검사기리셋',
        "y_Winding_Vision-표면(-) 검사기리셋-Pancake_Defect Qty",
        # 'Vision - PressForming 피드백 없음',
        "y_Winding_Vision-PressForming 피드백 없음-Jelly Roll_Defect Qty",
        # 'Vision - 음극 표면 비전 피드백 없음',
        "y_Winding_Vision-음극 표면 비전 피드백 없음-Jelly Roll_Defect Qty",
        # 'Vision - 양극 표면 비전 피드백 없음',
        "y_Winding_Vision-양극 표면 비전 피드백 없음-Jelly Roll_Defect Qty",
        # 'Vision - 음극 탭 비전 피드백 없음',
        "Y_SV_Winding_Vision-음극 탭 비전 피드백 없음-Jelly Roll_Defect Qty",
        "y_Winding_Vision-음극 탭 비전 피드백 없음-Jelly Roll_Defect Qty",
        # 'Vision - 양극 탭 비전 피드백 없음',
        "Y_SV_Winding_Vision-양극 탭 비전 피드백 없음-Jelly Roll_Defect Qty",
        "y_Winding_Vision-양극 탭 비전 피드백 없음-Jelly Roll_Defect Qty",
        "Vision - P8 비전 피드백 없음",
        "Vision - P7 비전 피드백 없음",
        "y_Winding_기타-Press Forming 압력-Jelly Roll_Defect Qty",  # '기타 - Press Forming 압력',
        # 'Vision - 외관(+) 코어 포밍',
        "Y_SV_Winding_Vision-외관(+) 코어 포밍-Jelly Roll_Defect Qty",
        "y_Winding_Vision-외관(+) 코어 포밍-Jelly Roll_Defect Qty",
        # 'Vision - 외관(+) 미들 포밍',
        "y_Winding_Vision-외관(+) 미들 포밍-Jelly Roll_Defect Qty",
        # 'Vision - 외관(+) 외곽 포밍',
        "y_Winding_Vision-외관(+) 외곽 포밍-Jelly Roll_Defect Qty",
        # 'Vision - 외관(-) 코어 포밍',
        "Y_SV_Winding_Vision-외관(-) 코어 포밍-Jelly Roll_Defect Qty",
        "y_Winding_Vision-외관(-) 코어 포밍-Jelly Roll_Defect Qty",
        # 'Vision - 외관(-) 미들 포밍',
        "y_Winding_Vision-외관(-) 미들 포밍-Jelly Roll_Defect Qty",
        # 'Vision - 외관(-) 외곽 포밍',
        "y_Winding_Vision-외관(-) 외곽 포밍-Jelly Roll_Defect Qty",
        # 'Vision - 외관(-) - 음극 탭 꽂힘',
        "y_Winding_Vision-외관(-) - 음극 탭 꽂힘-Jelly Roll_Defect Qty",
        # 'Vision - 외관(+) - 양극 탭 꽂힘',
        "y_Winding_Vision-외관(+) - 양극 탭 꽂힘-Jelly Roll_Defect Qty",
        # 'Vision - P9-탭 꽂힘검사기 피드백 없음',
        "y_Winding_Vision-P9-탭 꽂힘검사기 피드백 없음-Jelly Roll_Defect Qty",
        # 'Vision - 표면(+) 폭치수',
        "Y_SV_Winding_Vision-표면(+) 폭치수-Pancake_Defect Qty",
        "y_Winding_Vision-표면(+) 폭치수-Pancake_Defect Qty",
        # 'Vision - 표면(-) 폭치수',
        "y_Winding_Vision-표면(-) 폭치수-Pancake_Defect Qty",
        # '투입량시스템 - C1(음극 양극 GAP)',
        "y_Winding_투입량시스템-C1(음극 양극 GAP)-Pancake_Defect Qty",
        # '투입량시스템 - S1(음극 분리막 GAP)',
        "y_Winding_투입량시스템-S1(음극 분리막 GAP)-Pancake_Defect Qty",
        # 'Vision - 사행 Vision_음극 커팅 Burr',
        "y_Winding_Vision-사행 Vision_음극 커팅 Burr-Jelly Roll_Defect Qty",
        # 'Vision - 사행 Vision_양극 커팅 Burr',
        "y_Winding_:Vision-사행 Vision_양극 커팅 Burr-Jelly Roll_Defect Qty",
        "Vision - 사행 Vision_음극 주름",
        # 'Vision - 사행 Vision_주름',
        "Y_SV_Winding_Vision-사행 Vision_주름-Jelly Roll_Defect Qty",
        "y_Winding_Vision-사행 Vision_주름-Jelly Roll_Defect Qty",
        # 'Vision - 사행 - 음극 탭 꽂힘',
        "Y_SV_Winding_Vision-사행 - 음극 탭 꽂힘-Jelly Roll_Defect Qty",
        "y_Winding_Vision-사행 - 음극 탭 꽂힘-Jelly Roll_Defect Qty",
        "y_Winding_Vision-사행 - 양극 탭 꽂힘-Jelly Roll_Defect Qty",  # 'Vision - 사행 - 양극 탭 꽂힘',
        # 'Vision - 사행 Vision_양극 이물',
        "y_Winding_Vision-사행 Vision_양극 이물-Jelly Roll_Defect Qty",
        "Vision - 사행 Vision_양극 이물",
        # 'Vision - 사행 Vision_음극 이물',
        "y_Winding_Vision-사행 Vision_음극 이물-Jelly Roll_Defect Qty",
    ],
}

SMALL_Y_CTQ_WINDING_2 = [
    # 데이터 소스 : 전수검사데이터(전극/조립/활성화, SPC+)
        'y_SPC_Assembly_Winding_*_HMI 상 Tab Pitch',
        '주행 롤러 ↔ 닙 롤러 간 거리',
        'Pre-forming 높이 [자동 보정]',
        '분리막 텐션',
        '양/음극 텐션',
        '사행 기준값 (자동보정)',
        '와인딩 속도',
        '와인딩 가속도',
        '커팅 타수',
        'Final Roller 시작 위치/종료 위치',
        'Final Roller 압력',
        '분리막 잔량 턴수',
        '그리퍼 압력(배출부 ~ 언,로더)',
        '권심 안착면(비대칭)',
        '투입자재 두께_양극 두께',
        '투입자재 두께_음극 두께 ',
        '투입자재 두께_분리막 두께 (자재 기인)',
        'WND_젤리롤_미스매치_코어 (=Core 양/음극 Gap (투입량))',
        '리폼핀 히터 온도',
        '권심 정회전 각도',
        '권심 역회전 각도',
        '배출 각도',
        '권심 타수',


    # 데이터 소스 : 검사불량이력데이터
    'HMI 상 Tab Pitch',
    'Air Blower 압력',
    'Air Jet 압력',

    # 데이터 소스 : 설비 파라미터(PV) 데이터'
    'Press Forming 전진량 (양극 방향)',
    'Press Forming 전진량 (음극 방향)'
]

SMALL_Y_CTQ_WINDING = {
    "SPC": [
        # 데이터 소스 : 전수검사데이터(전극/조립/활성화, SPC+)
        "양극 표면 & 탭 검사기",
        "음극 표면 & 탭 검사기",
        "양/음극 주행 Forming 검사기",
        "J/R 외관&외경 검사기",
        "J/R Forming 검사기",
        "Inline-CT",
    ],
    "검사불량이력": [
        # 데이터 소스 : 검사불량이력데이터
        "권취 사행 검사기",
    ],
    "PV": [
        # 데이터 소스 : 설비 파라미터(PV) 데이터
        "총고 측정기",
    ],
}

SMALL_Y_DEFECT_ASSEMBLY = {
    "검사불량이력": [
        # (1) 검사불량데이터상 고빈도 불량코드
        # 데이터 소스 : 검사불량이력데이터 / MES
        "TTPHGT_C1",
        "TTPHGT_C2",
        "RVTNWD",  # 치수
        "WDBLTH_A1",  # 치수
        "WDBLTH_A2",  # 치수
        "WDBLTH_A3",  # 치수
        "WDBLTH_A4",  # 치수
        "TTPHGT_C1",  # 치수
        "TTPHGT_C2",  # 치수
        "BEDCTM",  # 외관
        "RVTWWD",  # 외관
        "TSDHGT_C1",  # 치수
        "TSDHGT_C2",  # 치수
        "CRCMSS",  # 외관
        "CRSHGT_A1",  # 치수
        "CRSHGT_A2",  # 치수
        "CTBOTH",  # 외관
        "CORIND_A1",  # 치수
        "WDBPOS_A1",  # 치수
        "WDBPOS_A2",  # 치수
        "WDBPOS_A3",  # 치수
        "WDBPOS_A4",  # 치수
        "CRCOWD",  # 외관
        "CTBOTH",  # 외관
    ],
    # 데이터 소스 : 전수검사데이터(조립/CIoT)
    "cIoT": ["주액량"],
    # (3) 주요 불량 유형에서 오는 불량 코드
    # 데이터 소스 : 전수검사데이터(전극/조립/활성화, SPC+)
    "SPC": [
        "CRCMSS",
        "TSDHGT_C1",
        "TSDHGT_C2",
        "TTPHGT_C1",
        "TTPHGT_C2",
        "RVTWWD",
        "CRSHGT_A1",
        "CRSHGT_A2",
    ],
}

SMALL_Y_CTQ_ASSEMBLY = {
    "LQC": [
        # (1) LQC
        "용접강도_CCW 양극 집전판 용접",
        "용접강도_CCW 음극 집전판 용접",
        "용접강도_ABW 음극 비딩 용접",
        "용접강도_CRW 양극 리벳 용접",
    ],
    "SPC": [
        # (2) 전수검사데이터 (전극/조립/활성화, SPC+)
        "TSDHGT_C1",  # 치수
        "TSDHGT_C2",  # 치수
        "CRSHGT_A1",
        "CRSHGT_A2",
        # (3) 계측데이터
        "BDNFLT",
        "CANHGT_N1",
        "CSZDIM_M1",
        "CSZDIM_M2",
    ],
}

SMALL_Y_DEFECT_WASHING = {
    # (1) 검사불량데이터상 고빈도 불량코드
    # TBU
    # (3) 주요 불량 유형에서 오는 불량 코드
    # 데이터 소스 : 전수검사데이터(전극/조립/활성화, SPC+)
    "SPC": ["CSDSCR", "VNTDEN", "CBTDEN", "CBTCTN", "RVTDEN", "RVTCTM", "RVTDEN"]
}

SMALL_Y_CTQ_ACTIVATION = {
    # 데이터 소스 : MES_Lot별 Cell Data
    "Lot별 Cell Data": [
        #"DisCharge #07 Fitted 용량(mAh)",
        'X_NFF_DisCharge #01_Capacity',
        'X_NFF_DisCharge #02_Capacity',
        'X_NFF_DisCharge #03_Capacity',
        'X_NFF_DisCharge #04_Capacity',
        'X_NFF_DisCharge #05_Capacity',
        'X_NFF_DisCharge #06_Capacity',
        'X_NFF_DisCharge #07_Capacity',
        # "Delta OCV #01 DOCV",
        # "Delta OCV #03~05 DOCV",
        # "Delta OCV #02 DOCV",
        'X_NFF_Delta OCV #02_Delta OCV',
        'X_NFF_Delta OCV #04_Delta OCV',
        'X_NFF_Delta OCV #01_Delta OCV',
        'X_NFF_Delta OCV #06_Delta OCV',
        'X_NFF_Delta OCV #05_Delta OCV',
        "IR-OCV #01 IMP",
        #"IR-OCV #01 전압",
        'X_NFF_IR-OCV #01_Average Voltage'
    ],
    # 데이터 소스 : 전수검사데이터(전극/조립/활성화)
    "NFF": [
        "DisCharge #07 Fitted 용량(mAh)",
        "Delta OCV #01 DOCV",
        "Delta OCV #03~05 DOCV",
        "Delta OCV #02 DOCV",
        "IR-OCV #01 IMP",
        "IR-OCV #01 전압",
    ],
}


"""
###TODO @yonju from here 
##여기 밑에 있는 애들을 위에 있는 애들에 매핑 하시고, 밑에 부분은 지워주세요

 'Y_SV_Coating_Sample-Development',
 'Y_SV_Coating_Sample-Development(Back)',
 'Y_SV_Coating_치수_폭(Top)',
 'Y_SV_Coating_조건조정-재조정(Top)',
 'Y_SV_Coating_기타 (Top)',
 'Y_SV_Coating_Sample-QA검사(Back)',
 'Y_SV_Coating_기타 (Back)',
 'Y_SV_Coating_연결-Back',
 'Y_SV_Coating_연결-Top',
 'Y_SV_Coating_Sample-자주검사(Top)',
 'Y_SV_Coating_조건조정-초기조건(Back)',
 'Y_SV_Coating_Sample-자주검사(Back)',
 'Y_SV_Coating_치수_폭(Back)',
 'Y_SV_Coating_조건조정-초기조건(Top)',
 'Y_SV_Coating_조건조정-재조정(Back)',
 'Y_SV_Coating_Sample-QA검사(Top)',
 'Y_SV_Coating_외관_Side Ring (Back)',
 'Y_SV_Mixing_Sample-TEST',
 'Y_SV_Mixing_세정-펌프',
 'Y_SV_Mixing_교체-믹서필터',
 'Y_SV_Mixing_기타-반제품',
 'Y_SV_Mixing_교체-탱크필터',
 'Y_SV_Mixing_Sample-자주검사',
 'Y_SV_Mixing_세정-배관',
 'Y_SV_Mixing_세정-자석',
 'Y_SV_Mixing_세정-탱크',
 'Y_SV_Mixing_세정-필터',
 'Y_SV_Mixing_세정-믹서',
 'Y_SV_Slitting_조건조정-반제품',
 'Y_SV_Slitting_연결-연결 테이프*',
 'Y_SV_Slitting_외관-변형-Burr-면상태',
 'Y_SV_Slitting_길이부족-반제품',
 'Y_SV_Slitting_길이초과-반제품',
 'Y_SV_Slitting_Sample-Development',
 'Y_SV_Slitting_외관-변형-High Edge-High Edge',
 'Y_SV_Slitting_기타',
 'Y_SV_Slitting_기타-바코드 부착',
 'Y_SV_Slitting_Sample-QA검사',
 'Y_SV_Slitting_NG라벨 수량',
 'Y_SV_Slitting_절연_핀홀',
 'Y_SV_Slitting_Sample-Test(기술)',
 'Y_SV_Roll Pressing_치수_두께',
 'Y_SV_Roll Pressing_길이부족-반제품*',
 'Y_SV_Roll Pressing_표면_미건조',
 'Y_SV_Roll Pressing_길이초과-반제품*',
 'Y_SV_Roll Pressing_Sample-QA검사',
 'Y_SV_Roll Pressing_연결-반제품',
 'Y_SV_Roll Pressing_기타',
 'Y_SV_Roll Pressing_표면_사이드링',
 'Y_SV_Roll Pressing_조건조정-반제품',
 'Y_SV_Roll Pressing_기타-반제품',
 'Y_SV_Roll Pressing_Sample-자주검사',
 'Y_SV_Roll Pressing_Sample-Development',
 'Y_SV_Roll Pressing_Sample-Test(기술)'


 'Y_SPC_y_Assembly_CBTCTM',
 'Y_SPC_y_Assembly_ISLFLP',
 'Y_SPC_y_Assembly_BEDBBD',
 'Y_SPC_y_Assembly_CORDMG',
 'Y_SPC_y_Assembly_CTBRVF',
 'Y_SPC_y_Assembly_CTBDEN',
 'Y_SPC_y_Washing_CBTCTM',
 'Y_SPC_y_Washing_CSDDEN'"""
